In [3]:
import pandas as pd

In [5]:
df_anime = pd.read_csv('anime.csv')
df_notas = pd.read_csv('rating.csv')

ParserError: Error tokenizing data. C error: Expected 7 fields in line 5, saw 8

In [5]:
display(df_anime.head())
df_notas.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,GintamaÂ°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [6]:
display(df_anime.info())
print('=='*40)
display(df_notas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

None

================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB

None

In [7]:

df = pd.merge(df_notas, df_anime.drop('rating', axis=1),on='anime_id' )
print(df.shape)
df.head()

(7813727, 8)

,user_id,anime_id,rating,name,genre,type,episodes,members
0,1,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,683297
1,3,20,8,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,683297
2,5,20,6,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,683297
3,6,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,683297
4,10,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,683297

In [8]:
df.groupby('name')['rating'].count().sort_values(ascending=False).head(600)

name
Death Note                         39340
Sword Art Online                   30583
Shingeki no Kyojin                 29584
Code Geass: Hangyaku no Lelouch    27718
Elfen Lied                         27506
                                   ...
Kore wa Zombie Desu ka? OVA         3517
Tokyo Godfathers                    3511
Mai-HiME                            3506
Devil Survivor 2 The Animation      3504
High School DxD Specials            3501
Name: rating, Length: 600, dtype: int64

In [9]:
notas = pd.DataFrame(df.groupby('name')['rating'].mean())
notas['numero de avaliaÃ§Ãµes'] = pd.DataFrame(df.groupby('name')['rating'].count())
notas['avaliaÃ§Ã£o mÃ©dia'] = pd.DataFrame(df.groupby('name')['rating'].mean().round(2))
notas

,rating,numero de avaliaÃ§Ãµes,avaliaÃ§Ã£o mÃ©dia
name,,,
&quot;0&quot;,2.769231,26,2.77
"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",0.000000,2,0.00
&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,5.774936,782,5.77
&quot;Bungaku Shoujo&quot; Memoire,6.155748,809,6.16
&quot;Bungaku Shoujo&quot; Movie,6.457980,1535,6.46
...,...,...,...
xxxHOLiC Kei,6.720774,3413,6.72
xxxHOLiC Movie: Manatsu no Yoru no Yume,6.313742,2365,6.31
xxxHOLiC Rou,6.403173,1513,6.40
xxxHOLiC Shunmuki,6.238602,1974,6.24
â¯,3.000000,6,3.00

In [10]:
genero = pd.DataFrame(data=df_anime[['name','genre']])
genero.set_index('name', inplace=True)
genero

                                                                                                genre
name
Kimi no Na wa.                                                   Drama, Romance, School, Supernatural
Fullmetal Alchemist: Brotherhood                    Action, Adventure, Drama, Fantasy, Magic, Mili...
GintamaÂ°                                            Action, Comedy, Historical, Parody, Samurai, S...
Steins;Gate                                                                          Sci-Fi, Thriller
Gintama&#039;                                       Action, Comedy, Historical, Parody, Samurai, S...
...                                                                                               ...
Toushindai My Lover: Minami tai Mecha-Minami                                                   Hentai
Under World                                                                                    Hentai
Violence Gekiga David no Hoshi                                                                 Hentai
Violence Gekiga Shin David no Hoshi: Inma Densetsu                                             Hentai
Yasuji no Pornorama: Yacchimae!!                                                               Hentai

[12294 rows x 1 columns]

In [11]:

def verificar_genero(lista_genero, string): 
    if any(x in string for x in lista_genero): 
        return True 
    else: 
        return False

In [13]:
def recomendar_anime(nome_do_anime, n):

   
    genero_anime = genero.loc[nome_do_anime].values[0].split(', ')
    
    
    cols = df_anime[df_anime['genre'].apply(lambda x: verificar_genero(genero_anime, str(x)))]['name'].tolist()

   
    matriz_de_animes = df[df['name'].isin(cols)].pivot_table(index='user_id', columns='name', values='rating')

    
    anime_nota = matriz_de_animes[nome_do_anime]

    
    anime_parecido = matriz_de_animes.corrwith(anime_nota)

    
    anime_correlacionado = pd.DataFrame(anime_parecido, columns=['correlaÃ§Ã£o'])

   
    anime_correlacionado = anime_correlacionado.join(notas[['numero de avaliaÃ§Ãµes', 'avaliaÃ§Ã£o mÃ©dia']])

   
    anime_correlacionado.dropna(inplace=True)

    
    animes_recomendados = anime_correlacionado[anime_correlacionado['numero de avaliaÃ§Ãµes'] > 3000].sort_values('correlaÃ§Ã£o', ascending=False)

   
    animes_recomendados= animes_recomendados.rename_axis('Animes recomendados')
    print(f'Anime escolhido: {nome_do_anime}')
    return animes_recomendados.head(n+1)

In [14]:
df.groupby('name')['rating'].count().sort_values(ascending=False).head()

name
Death Note                         39340
Sword Art Online                   30583
Shingeki no Kyojin                 29584
Code Geass: Hangyaku no Lelouch    27718
Elfen Lied                         27506
Name: rating, dtype: int64

In [15]:
recomendar_anime('Death Note', 5)

Anime escolhido: Death Note

,correlaÃ§Ã£o,numero de avaliaÃ§Ãµes,avaliaÃ§Ã£o mÃ©dia
Animes recomendados,,,
Death Note,1.000000,39340,7.56
Claymore,0.713321,12254,6.82
Higurashi no Naku Koro ni Kai,0.708664,9167,7.08
Beelzebub,0.707432,5871,6.58
Darker than Black: Kuro no Keiyakusha,0.705980,15591,7.01
Blood+,0.705211,7496,6.46

In [25]:
recomendar_anime('High School DxD',5)

Anime escolhido: High School DxD

,correlaÃ§Ã£o,numero de avaliaÃ§Ãµes,avaliaÃ§Ã£o mÃ©dia
Animes recomendados,,,
High School DxD,1.000000,14538,6.33
High School DxD New,0.871457,9303,6.46
Sekirei: Pure Engagement,0.792569,5221,6.07
CÂ³,0.784924,3714,5.52
Kore wa Zombie Desu ka? of the Dead,0.782128,7644,6.25
Sora no Otoshimono: Tokeijikake no Angeloid,0.781324,3161,6.36